name: Deploy on remote dev server
on:
  push:
    branches: [integration]
  pull_request:
    branches: [integration]
    types: [closed]

jobs: 
  build:
    name: build image and deploy
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
    - name: Copy folder content recursively to remote
      uses: garygrossgarten/github-action-scp@release
      with:
        local: ./
        remote: ${{ secrets.REMOTE_DIR }}cranach-api
        host: ${{ secrets.REMOTE_DEV_HOST }}
        username: ${{ secrets.SSH_USER }}
        password: ${{ secrets.SSH_PASSWORD }}
        rm: true
    - name: git checkout integration via SSH
      uses: appleboy/ssh-action@master
      with:
        script: |
          cd ${{ secrets.REMOTE_DIR }}cranach-api
          git checkout integration
        host: ${{ secrets.REMOTE_HOST }}
        username: ${{ secrets.SSH_USER }}
        password: ${{ secrets.SSH_PASSWORD }}
    - name: docker-compose stop via SSH
      uses: appleboy/ssh-action@master
      with:
        script: |
          cd ${{ secrets.REMOTE_DIR }}cranach-docker
          docker-compose stop api
        host: ${{ secrets.REMOTE_DEV_HOST }}
        username: ${{ secrets.SSH_USER }}
        password: ${{ secrets.SSH_PASSWORD }}  
    - name: docker-compose up -d api via OPEN SSH Private Key
      uses: appleboy/ssh-action@master
      with:
        script: |
          cd ${{ secrets.REMOTE_DIR }}cranach-docker
          docker-compose -f docker-compose.yml -f docker-compose.prod.yml up -d api
        host: ${{ secrets.REMOTE_DEV_HOST }}
        username: ${{ secrets.SSH_USER }}
        password: ${{ secrets.SSH_PASSWORD }}
