name: Docker Compose Actions Workflow
on: [push, pull_request]
jobs: 
  build:
    name: build image and deploy
    runs-on: ubuntu-latest
    steps:
    - name: Copy folder content recursively to remote
      uses: garygrossgarten/github-action-scp@release
      with:
        local: ./
        remote: ${{ secrets.REMOTE_DIR }}cranach-api
        host: ${{ secrets.REMOTE_HOST }}
        username: ${{ secrets.SSH_USER }}
        password: ${{ secrets.SSH_PASSWORD }}
      # - name: docker-compose stop via OPEN SSH Private Key
      # uses: garygrossgarten/github-action-ssh@release
      # with:
      #   command: docker-compose stop -d
      #   host: ${{ secrets.REMOTE_HOST }}
      #   username: ${{ secrets.SSH_USER }}
      #   password: ${{ secrets.PASSWORD }}  
      # - name: docker-compose up -d via OPEN SSH Private Key
      # uses: garygrossgarten/github-action-ssh@release
      # with:
      #   command: docker-compose up -d
      #   host: ${{ secrets.HOST }}
      #   username: ${{ secrets.SSH_USER }}
      #   password: ${{ secrets.PASSWORD }}
    #   - uses: actions/checkout@v2
    #   - name: Build the stack
    #     run: docker-compose up -d
